runtime: python38
instance_class: F4
service: REPLACE_ME

inbound_services:
  - warmup

env_variables:
  DEBUG: "0"
  DJANGO_SETTINGS_MODULE: "service.settings"
  SECRET_KEY: "REPLACE_ME"
  SERVICE_NAME: "REPLACE_ME"
  SERVICE_PROTOCOL: "https"
  SERVICE_DOMAIN: "www.codeforlife.education"
  SERVICE_PORT: "443"
