[tool.black]
line-length = 80
extend-exclude = ".*/migrations/.*py"

[tool.pytest.ini_options]
env = ["DJANGO_SETTINGS_MODULE=service.settings", "SERVICE_NAME=sso"]

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
check_untyped_defs = true
mypy_path = "../../codeforlife-package-python"

[tool.django-stubs]
django_settings_module = "service.settings"

[tool.pylint.main]
init-hook = "import os, sys; sys.path.append(os.getcwd())"

[tool.pylint.format]
max-line-length = 80

[tool.pylint.MASTER]
ignore-paths = [".*/migrations/.*py"]
load-plugins = "pylint_django"
django-settings-module = "service.settings"

[tool.isort]
profile = "black"
line_length = 80
skip_glob = ["**/migrations/*.py"]
